version: 0.0
os: linux

files:
  - source: /
    destination: /opt/app
    overwrite: yes
permissions:
  - object: /opt/app/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: /scripts/run_new_was.sh
      timeout: 120
      runas: root
    - location: /scripts/health_check.sh
      timeout: 120
      runas: root
    - location: /scripts/switch.sh
      timeout: 120
      runas: root