spring:
  profiles:
    active: local
    include:
      - aws
      - credentials
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  freemarker:
    cache: false
  jwt:
    secret: govlepel@$&

logging:
    level:
      com:
        amazonaws:
          util:
            EC2MetadataUtils: error


server:
  port: 8081